export const questions: { [month: number]: { [day: number]: string } } = {
  0: {
    1: "TODO",
    2: "TODO",
    3: "TODO",
    4: "TODO",
    5: "TODO",
    6: "TODO",
    7: "TODO",
    8: "TODO",
    9: "TODO",
    10: "TODO",
    11: "TODO",
    12: "TODO",
    13: "TODO",
    14: "TODO",
    15: "TODO",
    16: "TODO",
    17: "TODO",
    18: "TODO",
    19: "TODO",
    20: "TODO",
    21: "TODO",
    22: "TODO",
    23: "TODO",
    24: "TODO",
    25: "TODO",
    26: "TODO",
    27: "TODO",
    28: "TODO",
    29: "TODO",
    30: "TODO",
    31: "TODO",
  },
  1: {
    1: "TODO",
    2: "TODO",
    3: "TODO",
    4: "TODO",
    5: "TODO",
    6: "TODO",
    7: "TODO",
    8: "TODO",
    9: "TODO",
    10: "TODO",
    11: "TODO",
    12: "TODO",
    13: "TODO",
    14: "TODO",
    15: "TODO",
    16: "TODO",
    17: "TODO",
    18: "TODO",
    19: "TODO",
    20: "TODO",
    21: "TODO",
    22: "TODO",
    23: "TODO",
    24: "TODO",
    25: "TODO",
    26: "TODO",
    27: "TODO",
    28: "TODO",
    29: "TODO",
  },
  2: {
    1: "TODO",
    2: "TODO",
    3: "TODO",
    4: "TODO",
    5: "TODO",
    6: "TODO",
    7: "TODO",
    8: "TODO",
    9: "TODO",
    10: "TODO",
    11: "TODO",
    12: "TODO",
    13: "TODO",
    14: "TODO",
    15: "TODO",
    16: "TODO",
    17: "TODO",
    18: "TODO",
    19: "TODO",
    20: "TODO",
    21: "TODO",
    22: "TODO",
    23: "TODO",
    24: "TODO",
    25: "TODO",
    26: "TODO",
    27: "TODO",
    28: "TODO",
    29: "TODO",
    30: "TODO",
    31: "TODO",
  },
  3: {
    1: "TODO",
    2: "TODO",
    3: "TODO",
    4: "TODO",
    5: "TODO",
    6: "TODO",
    7: "TODO",
    8: "TODO",
    9: "TODO",
    10: "TODO",
    11: "TODO",
    12: "TODO",
    13: "TODO",
    14: "TODO",
    15: "TODO",
    16: "TODO",
    17: "TODO",
    18: "TODO",
    19: "TODO",
    20: "TODO",
    21: "TODO",
    22: "TODO",
    23: "TODO",
    24: "TODO",
    25: "TODO",
    26: "TODO",
    27: "TODO",
    28: "TODO",
    29: "TODO",
    30: "TODO",
  },
  4: {
    1: "TODO",
    2: "TODO",
    3: "TODO",
    4: "TODO",
    5: "TODO",
    6: "TODO",
    7: "TODO",
    8: "TODO",
    9: "TODO",
    10: "TODO",
    11: "TODO",
    12: "TODO",
    13: "TODO",
    14: "TODO",
    15: "TODO",
    16: "TODO",
    17: "TODO",
    18: "TODO",
    19: "TODO",
    20: "TODO",
    21: "TODO",
    22: "TODO",
    23: "TODO",
    24: "TODO",
    25: "TODO",
    26: "TODO",
    27: "TODO",
    28: "TODO",
    29: "TODO",
    30: "TODO",
    31: "TODO",
  },
  5: {
    1: "This is what I would do if I would have enough courage",
    2: "Rant time - write it down to get it out of your head",
    3: "This is what I would love to snack right now",
    4: "The current color of my bed linen",
    5: "The first thing I see when I look behind me",
    6: "The person I kissed most recently",
    7: "For this occasion I have dressed all up recently",
    8: "This is why I'm prooud of myself right now",
    9: "This is what I would like to have mooooore of",
    10: "Rewind - if I could I would have done this differently",
    11: "With these 3 people I would move into a shared house immediately",
    12: "I used these care products already today",
    13: "This is the place where my phone lies right now",
    14: "My current day in hashtags",
    15: "This was different today than any other day",
    16: "This fruit I ate most recently",
    17: "This I can't wait for anymore",
    18: "When I look around, I'm being reminded about this to-do",
    19: "This is what I have printed most recently",
    20: "TODO",
    21: "My to-do list for today",
    22: "My current hair color",
    23: "This quote matches my life right now",
    24: "My current idol",
    25: "A dish made from my current fridge contents",
    26: "This is how much sleep I had last night",
    27: "This is how fit I feel right now",
    28: "This is my relationship status",
    29: "I laughed about this really hard recently",
    30: "These things lie on my bedside table right now",
  },
  6: {
    1: "TODO",
    2: "TODO",
    3: "TODO",
    4: "TODO",
    5: "TODO",
    6: "TODO",
    7: "TODO",
    8: "TODO",
    9: "TODO",
    10: "TODO",
    11: "TODO",
    12: "TODO",
    13: "TODO",
    14: "TODO",
    15: "TODO",
    16: "TODO",
    17: "TODO",
    18: "TODO",
    19: "TODO",
    20: "TODO",
    21: "TODO",
    22: "TODO",
    23: "TODO",
    24: "TODO",
    25: "TODO",
    26: "TODO",
    27: "TODO",
    28: "TODO",
    29: "TODO",
    30: "TODO",
    31: "TODO",
  },
  7: {
    1: "TODO",
    2: "TODO",
    3: "TODO",
    4: "TODO",
    5: "TODO",
    6: "TODO",
    7: "TODO",
    8: "TODO",
    9: "TODO",
    10: "TODO",
    11: "TODO",
    12: "TODO",
    13: "TODO",
    14: "TODO",
    15: "TODO",
    16: "TODO",
    17: "TODO",
    18: "TODO",
    19: "TODO",
    20: "TODO",
    21: "TODO",
    22: "TODO",
    23: "TODO",
    24: "TODO",
    25: "TODO",
    26: "TODO",
    27: "TODO",
    28: "TODO",
    29: "TODO",
    30: "TODO",
    31: "TODO",
  },
  8: {
    1: "TODO",
    2: "TODO",
    3: "TODO",
    4: "TODO",
    5: "TODO",
    6: "TODO",
    7: "TODO",
    8: "TODO",
    9: "TODO",
    10: "TODO",
    11: "TODO",
    12: "TODO",
    13: "TODO",
    14: "TODO",
    15: "TODO",
    16: "TODO",
    17: "TODO",
    18: "TODO",
    19: "TODO",
    20: "TODO",
    21: "TODO",
    22: "TODO",
    23: "TODO",
    24: "TODO",
    25: "TODO",
    26: "TODO",
    27: "TODO",
    28: "TODO",
    29: "TODO",
    30: "TODO",
  },
  9: {
    1: "TODO",
    2: "TODO",
    3: "TODO",
    4: "TODO",
    5: "TODO",
    6: "TODO",
    7: "TODO",
    8: "TODO",
    9: "TODO",
    10: "TODO",
    11: "TODO",
    12: "TODO",
    13: "TODO",
    14: "TODO",
    15: "TODO",
    16: "TODO",
    17: "TODO",
    18: "TODO",
    19: "TODO",
    20: "TODO",
    21: "TODO",
    22: "TODO",
    23: "TODO",
    24: "TODO",
    25: "TODO",
    26: "TODO",
    27: "TODO",
    28: "TODO",
    29: "TODO",
    30: "TODO",
    31: "TODO",
  },
  10: {
    1: "TODO",
    2: "TODO",
    3: "TODO",
    4: "TODO",
    5: "TODO",
    6: "TODO",
    7: "TODO",
    8: "TODO",
    9: "TODO",
    10: "TODO",
    11: "TODO",
    12: "TODO",
    13: "TODO",
    14: "TODO",
    15: "TODO",
    16: "TODO",
    17: "TODO",
    18: "TODO",
    19: "TODO",
    20: "TODO",
    21: "TODO",
    22: "TODO",
    23: "TODO",
    24: "TODO",
    25: "TODO",
    26: "TODO",
    27: "TODO",
    28: "TODO",
    29: "TODO",
    30: "TODO",
  },
  11: {
    1: "TODO",
    2: "TODO",
    3: "TODO",
    4: "TODO",
    5: "TODO",
    6: "TODO",
    7: "TODO",
    8: "TODO",
    9: "TODO",
    10: "TODO",
    11: "TODO",
    12: "TODO",
    13: "TODO",
    14: "TODO",
    15: "TODO",
    16: "TODO",
    17: "TODO",
    18: "TODO",
    19: "TODO",
    20: "TODO",
    21: "TODO",
    22: "TODO",
    23: "TODO",
    24: "TODO",
    25: "TODO",
    26: "TODO",
    27: "TODO",
    28: "TODO",
    29: "TODO",
    30: "TODO",
    31: "TODO",
  },
};
