export const questions: { [month: number]: { [day: number]: string } } = {
  0: {
    1: "My resolutions for this year",
    2: "I'm currently asking myself this question a lot",
    3: "This is currently to the left of me",
    4: "My current battery level",
    5: "I recently did this myself",
    6: "I have appetite on the following right now",
    7: "TODO",
    8: "I most recently saw this movie",
    9: "My mood today in one word",
    10: "The color of my underwear today",
    11: "My last dream that I can remember",
    12: "Something I bought, but haven't used yet",
    13: "I would love to travel back to this point in my past",
    14: "I am turning into a coin - heads or tails?",
    15: "If I could, I would move into this city right now",
    16: "Is there snow outside right now?",
    17: "I'm really proud of this today",
    18: "The first word that comes to my mind right now",
    19: "I would like to meet this person some time",
    20: "I got out of bed at this time today",
    21: "This is what's currently in my bag",
    22: "This is what it looks like when I type my name with my eyes closed",
    23: "My current favorite saying",
    24: "My last night was ...",
    25: "I'm currently smelling like this",
    26: "TODO",
    27: "I would love to read the mind of this person",
    28: "TODO",
    29: "This is how I feel right now",
    30: "This is a rumor that is currently going around",
    31: "I promise the following to myself",
  },
  1: {
    1: "This is how long I can hold my breath",
    2: "This is the person I talked last to",
    3: "TODO",
    4: "This is something that tasted awful recently",
    5: "This is the reason I cried the last time",
    6: "This is what is currently making me shine",
    7: "This is what makes today special",
    8: "I would like to treat myself with this soon",
    9: "I hope that these things will never change",
    10: "TODO",
    11: "This is the last switch I operated",
    12: "I would like to be at this place right now",
    13: "I'm currently thinking about the following",
    14: "I despise this word",
    15: "I'm currently owning this many pair of shoes",
    16: "I would like to get a tattoo of this at some point",
    17: "TODO",
    18: "These are the best football teams right now",
    19: "I already created these many snow sculptures this winter",
    20: "This show is making me pretty upset at the moment",
    21: "This is what I will probably do one year from now",
    22: "This is what is currently on my key chain",
    23: "This is what I appreciate the most about my friends right now",
    24: "My absolute favorite tv show",
    25: "This is what you can see on my last picture on my phone",
    26: "I laughed about this today",
    27: "This is a word where I'm never sure how it is being written properly",
    28: "4 things in my vicinity - brought together in a poem!",
    29: "Is this year a leap year?",
  },
  2: {
    1: "This what I most recently returned",
    2: "This is the latest app that I downloaded",
    3: "My current favorite piece of clothing",
    4: "Being a child again - this is what I do immediately",
    5: "This is why I was at the doctors most recently",
    6: "A short poem about my day",
    7: "This is what I would like to ask my future self",
    8: "This song is currently the absolute hit!",
    9: "This is how it looks like in my wardrobe right now",
    10: "This is what I'm currently sitting on",
    11: "This was the reason why I recently had to take a detour",
    12: "I would have loved to throw this device out of the window recently",
    13: "Something delicious, that is waiting for my in my fridge",
    14: "I should call this person again",
    15: "TODO",
    16: "These are my current flat mates",
    17: "This was the last movie I saw in the cinema",
    18: "TODO",
    19: "TODO",
    20: "A website I visit very often",
    21: "I love to say thank you to this person",
    22: "The time I got to bed last night",
    23: "I currently have this amount of cash in my pockets",
    24: "This was the paper I most recently punched",
    25: "Today's weather",
    26: "My current phone wallpaper shows ...",
    27: "TODO",
    28: "The last person I had a call with",
    29: "I'm currently saving for this",
    30: "I recently bought this magazine",
    31: "How warm is it today?",
  },
  3: {
    1: "I really fell for this april fool's joke",
    2: "I'm currently planning the following trip",
    3: "A quote from today",
    4: "A good reason to party today",
    5: "Today's color of my socks",
    6: "My catchy tune of the day",
    7: "This is how often I write into this diary",
    8: "This is why I frittered away my time today",
    9: "This is what I had for lunch today",
    10: "The last e-mail I received",
    11: "This is what I have thrown into my laundry today",
    12: "This is the last animal I petted",
    13: "Time to eavesdrop! This is what I hear if I open the window",
    14: "TODO",
    15: "I'd love to have more time for this right now",
    16: "My current shopping list",
    17: "Being invisible - this is what I would do immediately",
    18: "I want to get rid of this for a long while",
    19: "This invoice is still open",
    20: "PSSST... A small secret",
    21: "This song gets on my nerves right now the most",
    22: "The topic of the last documentary I watched",
    23: "This was the document I last signed",
    24: "TODO",
    25: "This is what I currently lent out to others",
    26: "I would love to cancel this appointment this week",
    27: "Take a deep breath. This is what it smells like right now",
    28: "I'm in love with ...",
    29: "When thinking about this, I have to grin immediately",
    30: "This is what's currently running on tv",
  },
  4: {
    1: "This is what I wrote on a post it today",
    2: "I would love to get in touch with this person again",
    3: "I see myself here one year from now",
    4: "Free mind space! Feel free to write down your thoughts",
    5: "My first thought when I woke up today",
    6: "I already climbed this number of stair steps today",
    7: "I already did this nice thing today",
    8: "TODO",
    9: "This was the last WhatsApp message I received",
    10: "This are all the places that I have been to today already",
    11: "The last contest I participated",
    12: "I'm currently using this word all the time",
    13: "This is what I last added into my calendar",
    14: "TODO",
    15: "I can't live without this thing in my life",
    16: "This is the jewelry I'm wearing today",
    17: "My plan for the next weekend",
    18: "If I close my eyes and start typing ...",
    19: "Pizza please! This is what I would put on it",
    20: "This is what I have currently borrowed from others",
    21: "I think this person thinks about me right now",
    22: "This is what I most recently rode with",
    23: "I'm currently quite excited due to this",
    24: "Time to ask yourself a question!",
    25: "I'm currently using the following device to type this ...",
    26: "This is what I would do if money would not matter",
    27: "This is still on my plan for today",
    28: "This is what I would call a new pet",
    29: "I'm currently living here",
    30: "There are currently these many things around me in a perimeter of 1 meter",
    31: "This is my current favorite human",
  },
  5: {
    1: "This is what I would do if I would have enough courage",
    2: "Rant time - write it down to get it out of your head",
    3: "This is what I would love to snack right now",
    4: "The current color of my bed linen",
    5: "The first thing I see when I look behind me",
    6: "The person I kissed most recently",
    7: "For this occasion I have dressed all up recently",
    8: "This is why I'm proud of myself right now",
    9: "This is what I would like to have mooooore of",
    10: "Rewind - if I could I would have done this differently",
    11: "With these 3 people I would move into a shared house immediately",
    12: "I used these care products already today",
    13: "This is the place where my phone lies right now",
    14: "My current day in hashtags",
    15: "This was different today than any other day",
    16: "This fruit I ate most recently",
    17: "This I can't wait for anymore",
    18: "When I look around, I'm being reminded about this to-do",
    19: "This is what I have printed most recently",
    20: "This is the latest alcoholic drink I had",
    21: "My to-do list for today",
    22: "My current hair color",
    23: "This quote matches my life right now",
    24: "My current idol",
    25: "A dish made from my current fridge contents",
    26: "This is how much sleep I had last night",
    27: "This is how fit I feel right now",
    28: "This is my relationship status",
    29: "I laughed about this really hard recently",
    30: "These things lie on my bedside table right now",
  },
  6: {
    1: "TODO",
    2: "Currently I'm using this shower gel",
    3: "This is the last thing I backed",
    4: "I see this when I look up right now",
    5: "This shocked me today",
    6: "This is the last person I made a pleasure",
    7: "This is the last thing I plugged into power",
    8: "I'd like to be this superhero",
    9: "TODO",
    10: "And the moral of today's story is ...",
    11: "This is the most important point of my today list today",
    12: "I already ate this sweet today",
    13: "My dream partner should be like this",
    14: "This is what's currently in my wallet",
    15: "I bet I already made this many kilometers today",
    16: "I would like to celebrate this big event soon",
    17: "I already got upset about this today",
    18: "My current favorite thing in my home",
    19: "This is how I wear my hair today",
    20: "This was the place where I was in a public swimming pool most recently",
    21: "My current favorite movie",
    22: "I love the following app at the moment",
    23: "A sentence about today - sdrawkcab",
    24: "I'm waiting on this at the moment",
    25: "This was the last person I followed on instagram",
    26: "This is what I broke most recently",
    27: "The most expensive thing that I recently got for myself",
    28: "This website I visited recently",
    29: "This person plays the biggest role in my life right now",
    30: "This is what a typical day dream of mine looks like",
    31: "I'm currently pushing these things ahead of me",
  },
  7: {
    1: "A moment of silence. What did you hear?",
    2: "To the sea side! Where were you the last time?",
    3: "My outfit today",
    4: "I would like to learn this",
    5: "I love these lyrics right now",
    6: "I would like to hug the following person right now",
    7: "I would like to less of this",
    8: "My motto for today",
    9: "This is what I ordered at my last restaurant visit",
    10: "This is where my next trip goes to",
    11: "TODO",
    12: "I would like to do the following again some time",
    13: "I can't do without the following at the moment",
    14: "The last YouTube video that I watched",
    15: "This is what I've lost last",
    16: "This is where I am currently at",
    17: "I would like to buy this for my home right now",
    18: "TODO",
    19: "TODO", // e.g. favorite animal right now
    20: "My mood today in 3 words",
    21: "I'm currently angry at this person! This is what I would like say to them",
    22: "This gives me strength right now",
    23: "My last weekend was ...",
    24: "I could empty the following store right now",
    25: "I recently made up with this person",
    26: "This is what my last nightmare was about",
    27: "I recently posted about this somewhere",
    28: "My pet - that I currently have or would like to have",
    29: "I was in these countries already this year",
    30: "I'm currently doing this sport",
    31: "A current story of my neighbours",
  },
  8: {
    1: "I already threw the following away today",
    2: "The last person I got a post card from",
    3: "This suprised me recently",
    4: "I laughed a lot about this joke",
    5: "My biggest dream that I'm currently pursuing",
    6: "The first thing I saw after waking up today",
    7: "My current nail color",
    8: "I already drank these many glasses of water today",
    9: "My most recent online purchase, that I sent back",
    10: "I was already at these places today",
    11: "I was upset about this today",
    12: "I'm currently very grateful for this",
    13: "This is the person that I got to know most recently",
    14: "This has been gifted to me recently",
    15: "For today, I'm wishing for the following weather",
    16: "My favorite magazine at the moment",
    17: "I'm working extra hard on this right now",
    18: "My mood today on a scale from 1 to 10",
    19: "I would love to meet these 3 celebrities",
    20: "I wish I had the following tasty food right now",
    21: "My latest bad buy",
    22: "These topics are in the news today",
    23: "This is something that went better than expected recently",
    24: "I laughed to tears about this lately",
    25: "I started with this lately",
    26: "I'm currently very relieved about this",
    27: "This is my favorite fruit right now",
    28: "I couldn't sleep recently due to this",
    29: "I was able to achieve this in the recent days",
    30: "This is the latest thing I hung up on my wall",
  },
  9: {
    1: "These were the last waters I swam in",
    2: "I'm wishing for the following for this month",
    3: "I would like to try this restaurant",
    4: "I wish this person would be with me right now",
    5: "This is where I went on my latest jaunt",
    6: "I couldn't care less about the following right now",
    7: "I'm currently addicted to this tv series",
    8: "I would like to know the following from my parents",
    9: "The funniest slip of the tongue that I had recently",
    10: "I was really shocked by these news",
    11: "These people would be able to hear me if I started singing loudly right now",
    12: "I would like to have this super talent",
    13: "I would like to play this again",
    14: "This is the last place I travelled to with a train",
    15: "My current phone",
    16: "Did you already shower today?",
    17: "I recently bought this for myself",
    18: "I would like to see this movie in the cinema right now",
    19: "The duration of my latest bath in the bathtub",
    20: "This is what can be seen on my last instagram post",
    21: "I'm currently reading these books",
    22: "This is what I got done well recently",
    23: "I would like to stop with the following",
    24: "TODO",
    25: "My alarm clock woke me up at this hour today",
    26: "I'm listening to this playlist on repeat right now",
    27: "This is what I've most recently seen on TV",
    28: "My current hair routine",
    29: "I should really take some time for this again soon",
    30: "This is what is currently to the right of me",
    31: "My current favorite activity",
  },
  10: {
    1: "I learned this today that will stick with me for the rest of my life",
    2: "I'm currently most happy about this",
    3: "This is how I feel today",
    4: "My agenda for today",
    5: "I recently apologized for this",
    6: "These are the names of my neighbours",
    7: "My hair is currently this long",
    8: "I'm already waiting for this event for a long time",
    9: "My goal for today",
    10: "My heart is currently beating especially for this",
    11: "People I know their phone numbers by heart",
    12: "The last party I attended",
    13: "The weather is currently like this",
    14: "Someone shared this with me recently",
    15: "I would love to have more talent in this",
    16: "This is what is currently under my bed",
    17: "This is what is worrying me right now",
    18: "I'm currently very comfortable doing the following",
    19: "This is how tall I am right now",
    20: "I would love to invent this some day",
    21: "The nicest compliment I got this week",
    22: "I would love to experience the following again from my past days",
    23: "I had my last portion of fries on ...",
    24: "I recently treated myself with this",
    25: "This person is good for me right now",
    26: "I recently missed this",
    27: "I would immediately do this - if I wouldn't have any obligations",
    28: "My favorite song right now",
    29: "A secret fantasy of mine",
    30: "The last message I sent",
  },
  11: {
    1: "I have this kind of advent calendar this year",
    2: "This is the meaning of christmas for me",
    3: "My favorite book right now",
    4: "This person is near me right now",
    5: "I already did this amount of sport today",
    6: "This is what I got from St. Nicholas today",
    7: "I like this about me right now",
    8: "I'm currently missing the following very much",
    9: "I would love to be this person for a day",
    10: "This is what is in my clipboard right now",
    11: "I would love to get more engaged in this at the moment",
    12: "I recently searched for this",
    13: "100 € found! I would do the following today with this money",
    14: "This is very trendy right now",
    15: "I already have these many christmas gifts at the moment",
    16: "A nice message that I received",
    17: "This was the last time I comforted someone",
    18: "I would go to this concert next",
    19: "My current wall color",
    20: "I'm currently spending most of my time with this",
    21: "I already backed these cookies this year",
    22: "I'm gifting the following this year",
    23: "TODO",
    24: "This is how I'm celebrating christmas eve today",
    25: "This is what's on the menu today",
    26: "I have watched these christmas movies in the past days",
    27: "This was a sentimental moment",
    28: "I learned the following this year",
    29: "This was the best song of this year",
    30: "This was the most beautiful experience for me this year",
    31: "These are my plans for new years eve today",
  },
};
