name: yearlydiary
on:
  - push

jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-lint-test
      cancel-in-progress: true
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4
      - uses: bahmutov/npm-install@v1
      - name: Ensure clean repository
        run: git diff --exit-code
      - name: Lint
        run: yarn lint
      - name: Unit Tests
        run: yarn test --ci
      - name: E2E Tests
        run: yarn test:e2e-ci
        working-directory: web
      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: test-artifacts
          path: web/test-results

  deploy:
    name: Deploy
    needs: test
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-deploy-web
    env:
      CI: true
    steps:
      - uses: actions/checkout@v4
      - name: Warm up yearlydiary database
        # Request a random diary page to ensure database connection is established
        run: curl -i https://yearlydiary.vercel.app/ci-warmup
      - name: Deploy to vercel (production)
        if: github.ref == 'refs/heads/main'
        uses: amondnet/vercel-action@v25.1.1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: "--prod"
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
      - name: Deploy to vercel (preview)
        if: github.ref != 'refs/heads/main'
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
  notify-on-failure:
    needs:
      - test
      - deploy
    runs-on: ubuntu-latest
    if: failure() # only run this job when any of the previous jobs fail.
    steps:
      - name: Notify through commit comment
        uses: peter-evans/commit-comment@v3
        with:
          body: "@peterjuras: The workflow failed!"
