name: yearlydiary
on:
  - push

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v3
      - uses: bahmutov/npm-install@v1
      - name: Ensure clean repository
        run: git diff --exit-code
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test --ci
